# permissions for end users to view auths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: container-registry-k8s-auth-controller
    app.kubernetes.io/managed-by: kustomize
  name: auth-viewer-role
rules:
  - apiGroups:
      - containerregistry.arthurvardevanyan.com
    resources:
      - auths
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - containerregistry.arthurvardevanyan.com
    resources:
      - auths/status
    verbs:
      - get
