# permissions for end users to edit auths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: container-registry-k8s-auth-controller
    app.kubernetes.io/managed-by: kustomize
  name: auth-editor-role
rules:
- apiGroups:
  - containerregistry.arthurvardevanyan.com
  resources:
  - auths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerregistry.arthurvardevanyan.com
  resources:
  - auths/status
  verbs:
  - get
