---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - containerregistry.arthurvardevanyan.com
    resources:
      - auths
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - containerregistry.arthurvardevanyan.com
    resources:
      - auths/finalizers
    verbs:
      - update
  - apiGroups:
      - containerregistry.arthurvardevanyan.com
    resources:
      - auths/status
    verbs:
      - get
      - patch
      - update
