apiVersion: containerregistry.arthurvardevanyan.com/v1beta1
kind: Auth
metadata:
  labels:
    app.kubernetes.io/name: container-registry-k8s-auth-controller
    app.kubernetes.io/managed-by: kustomize
  name: auth-sample
spec:
  # TODO(user): Add fields here
