apiVersion: containerregistry.arthurvardevanyan.com/v1beta1
kind: Auth
metadata:
  name: example-quay
  namespace: smoke-tests
spec:
  serviceAccount: wif-test
  secretName: quay
  containerRegistry: quay
  audience: openshift
  quay:
    robotAccount: "arthurvardevanyan+push"
    url: quay.io
---
apiVersion: containerregistry.arthurvardevanyan.com/v1beta1
kind: Auth
metadata:
  name: example
  namespace: smoke-tests
spec:
  containerRegistry: googleArtifactRegistry
  secretName: artifact-registry-auth
  serviceAccount: wif-test
  audience: openshift
  googleArtifactRegistry:
    registryLocation: us-central1
    fileName: credentials_config.json
    objectName: google-wif-config
    serviceAccount: wif-test
    type: configMap
---
apiVersion: containerregistry.arthurvardevanyan.com/v1beta1
kind: Auth
metadata:
  name: example-inline
  namespace: smoke-tests
spec:
  containerRegistry: googleArtifactRegistry
  secretName: artifact-registry-auth-inline
  serviceAccount: wif-test
  audience: openshift
  googleArtifactRegistry:
    registryLocation: us-central1
    googleServiceAccount: wif-test@afr-operator-5560235161.iam.gserviceaccount.com
    googlePoolProject: "448527874743"
    googlePoolName: afr-operator-pool
    googleProviderName: afr-operator-provider
    type: inline
